package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import javafx.scene.control.Button;
import javafx.scene.control.TextField;

import java.net.URL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.ArrayList;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextArea;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.input.InputMethodEvent;

public class SampleController implements Initializable {
	@FXML
	private ImageView imgAnimal;
	@FXML
	private ComboBox<String> cbFamilia;
	@FXML
	private ComboBox<String> cbOrdre;
	@FXML
	private TextField txtNom;
	@FXML
	private TextField txtEspecia;
	@FXML
	private ComboBox<String> cbEstat;
	@FXML
	private TextArea txaDescripcio;
	@FXML
	private Button btnDesa;
	@FXML
	private Button btnAnterior;
	@FXML
	private Button btnSeguent;
	
	private Connection con = null;
	private ArrayList<Animal> llistaAnimals = new ArrayList<Animal>();
	private Statement consulta;
		
	private boolean obreBDD(){
		boolean obert =false;
		try {
			Class.forName("com.mysql.jdbc.Driver");
			
			//con = DriverManager.getConnection("jdbc:mysql://192.168.4.1/traductor", "foot", "ball");
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/reptils", "foot", "ball");
			obert=true;
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return obert;
	}

	public void initialize(URL arg0, ResourceBundle arg1) {
		//obrir base de dades
		obreBDD();
		try {
			consulta = con.createStatement();
			//select a la taula familia
			ResultSet resultat = consulta.executeQuery("SELECT * FROM families");
			//omplir el cbFamilia amb els valors de la bdd
			cbFamilia.setValue("Tria una familia");
			while(resultat.next()){
				cbFamilia.getItems().addAll(resultat.getString("nom"));	
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	// Event Listener on ComboBox[#cbFamilia].onAction
	@FXML
	public void carregaOrdres(ActionEvent event) {
		if(obreBDD()){
			cbOrdre.getItems().clear();
			int index=cbFamilia.getSelectionModel().getSelectedIndex()+1;
			//seleccionar els ordres que pertanyen a la familia
			try {
				consulta = con.createStatement();
				ResultSet resultat = consulta.executeQuery("SELECT nom FROM ordres WHERE familia="+index);
				//posa-los al cbOrdres
				
				while(resultat.next()){
					cbOrdre.getItems().addAll(resultat.getString("nom"));
				}
				cbOrdre.setValue("Tria un ordre de la familia");
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}			
		}
	}
	// Event Listener on ComboBox[#cbOrdre].onAction
	@FXML
	public void carregaAnimals(ActionEvent event) {
		//Fer un select de tots els animals de l'ordre seleccionat
		//posar-los a la llistaAnimals
		//mostrar el primer (omplir tots els camps)
	}
	
	@FXML
	public void habilitaDesa(InputMethodEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnDesa].onMouseClicked
	@FXML
	public void desaAnimal(MouseEvent event) {
		// obrir la bdd
		//desar la nova info de lanimal
		//recarregar la llistaAnimals (esborrar i tornar a omplit
	}
	// Event Listener on Button[#btnAnterior].onMouseClicked
	@FXML
	public void animalAnterior(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSeguent].onMouseClicked
	@FXML
	public void animalSeguent(MouseEvent event) {
		// TODO Autogenerated
	}
}
